### ISSUE TITLE
Release 0.1.5

### ISSUE THREAD

**Issue by mmniaziqb** [dkruchinin/sanic-prometheus#13]
Hi can you please prepare new release with #11 or above

**Comment by SirEdvin** [comment]
@dkruchinin Can you please release a new version?

**Comment by dkruchinin** [comment]
@SirEdvin Thanks for the reminder! I have the memory of a goldfish :)

**Comment by dkruchinin** [comment]
Commit :: https://github.com/dkruchinin/sanic-prometheus/commit/dd384b919aadc78c6cb15250893cb27f56a5ded2
