### ISSUE TITLE
Custom metrics

### ISSUE THREAD

**Issue by ahopkins** [dkruchinin/sanic-prometheus#14]
Nice work on this. I like the direction that you are headed. I'll be honest, I have not looked too deeply into the code base yet, but have you put any thought into providing some sort of an API to providing custom metrics?

For example, it would be nice if I had some sort of a decorator, or something that would allow me to report back a custom metric on a particular endpoint. In particular, I am thinking about a way to report to prometheus the number of live sessions and websocket connections are open.

**Comment by SirEdvin** [comment]
@ahopkins 
sanic_prometheus uses [prometheus_clitn](https://github.com/prometheus/client_python), so you can just add custom mertic in every part of you code and it will be automatically exposed. 

Try, for exampe, [this](https://gist.github.com/SirEdvin/c41461c82dd2b2c32e42a49df79293a2) snippet.

**Comment by ahopkins** [comment]
Beautiful. Thank you.
