### ISSUE TITLE
Broken with new prometheus-client 0.5.0

### ISSUE THREAD

**Issue by aviv-ebates** [dkruchinin/sanic-prometheus#17]
`prometheus-client` released 0.5.0 a few days ago, and it breaks the api.

Should probably limit the version in `setup.py` to `prometheus-client ~= 0.4.2` to install the latest-known-good version.

**Comment by dkruchinin** [comment]
Fixed:
* version 0.1.6 -- restricts prometheus-client dependency to the latest known-good version (🙏 @aviv-ebates ) 
* version 0.1.7 -- works fine with prometheus-client >= 0.5.0, not backwards compatible (🙏 myself)
