### ISSUE TITLE
Exception on OPTIONS

### ISSUE THREAD

**Issue by dnutiu** [dkruchinin/sanic-prometheus#22]
Hello,

I get a `KeyError: '__START_TIME__'` when I send an OPTIONS request, maybe the library should ignore the OPTIONS req. I'm also using it together with `Sanic-Cors`.

**Comment by dnutiu** [comment]
Made a PR:https://github.com/dkruchinin/sanic-prometheus/pull/23

My PR could be changed to add a list of predefined ignored request/response methods.

**Comment by dkruchinin** [comment]
Thank you @dnutiu, I've merged your PR with master 👍
