### ISSUE TITLE
Error on shutdown when adding the monitor

### ISSUE THREAD

**Issue by ram-argus** [dkruchinin/sanic-prometheus#7]
2017-12-27 13:35:38,132 asyncio ERROR Task was destroyed but it is pending!
task: <Task pending coro=<make_periodic_memcollect_task.<locals>.collector() running at /usr/local/lib/python3.5/dist-packages/sanic_prometheus/metrics.py:42> wait_for=<Future pending cb=[Task._wakeup()]>>

the error disappear when monitor(app).expose_endpoint() is not used

**Comment by SirEdvin** [comment]
@ram-argus Did you tried the last release with a fix from #4 ?

**Comment by ram-argus** [comment]
wow, already fixed. thanks!
